### ISSUE TITLE
Projectorganizer crash

### ISSUE THREAD

**Issue by kugel-** [geany/geany-plugins#554]
When closing a project:

```
Thread 1 "geany" received signal SIGSEGV, Segmentation fault.
0x00007fffe0016aa2 in expand_path (utf8_expanded_path=0x13cf090 "", select=select@entry=0) at prjorg-sidebar.c:1168
1168		foreach_slist (elem, prj_org->roots)
(gdb) bt
#0  0x00007fffe0016aa2 in expand_path (utf8_expanded_path=0x13cf090 "", select=select@entry=0) at prjorg-sidebar.c:1168
#1  0x00007fffe0016c5f in expand_on_idle (ptr=0x8659a0) at prjorg-sidebar.c:1224
#2  0x00007ffff529945a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff5299810 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff5299b32 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff724ed05 in gtk_main () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff79a7a40 in main_lib (argc=<optimized out>, argv=<optimized out>) at ../../src/libmain.c:1236
#7  0x00007ffff4cad511 in __libc_start_main () at /usr/lib/libc.so.6
#8  0x000000000040061a in _start ()
```

Reverting 8111515e7ce4bbc991f31e497a978cb0c56d9b90 helps

**Comment by kugel-** [comment]
@techee ^

**Comment by codebrainz** [comment]
Is it #549?

**Comment by kugel-** [comment]
Yea, sorry.
